/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AIPingRequest } from '../model/models';
import { AIPingResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AiServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * Diagnostic ping to the Anthropic API.
     * @endpoint post /api/v1/ai/ping/
     * @param aIPingRequest 
     */
    aiPingCreate(aIPingRequest?: AIPingRequest, extraHttpRequestParams?: any): Observable<AIPingResponse>;

}
