export * from './ai.service';
import { AiService } from './ai.service';
export * from './ai.serviceInterface';
export * from './attachments.service';
import { AttachmentsService } from './attachments.service';
export * from './attachments.serviceInterface';
export * from './attendance-statuses.service';
import { AttendanceStatusesService } from './attendance-statuses.service';
export * from './attendance-statuses.serviceInterface';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './auth.serviceInterface';
export * from './energy-segments.service';
import { EnergySegmentsService } from './energy-segments.service';
export * from './energy-segments.serviceInterface';
export * from './energy-systems.service';
import { EnergySystemsService } from './energy-systems.service';
export * from './energy-systems.serviceInterface';
export * from './events.service';
import { EventsService } from './events.service';
export * from './events.serviceInterface';
export * from './exercises.service';
import { ExercisesService } from './exercises.service';
export * from './exercises.serviceInterface';
export * from './health.service';
import { HealthService } from './health.service';
export * from './health.serviceInterface';
export * from './invitations.service';
import { InvitationsService } from './invitations.service';
export * from './invitations.serviceInterface';
export * from './join-magic.service';
import { JoinMagicService } from './join-magic.service';
export * from './join-magic.serviceInterface';
export * from './join-requests.service';
import { JoinRequestsService } from './join-requests.service';
export * from './join-requests.serviceInterface';
export * from './levels.service';
import { LevelsService } from './levels.service';
export * from './levels.serviceInterface';
export * from './me.service';
import { MeService } from './me.service';
export * from './me.serviceInterface';
export * from './members.service';
import { MembersService } from './members.service';
export * from './members.serviceInterface';
export * from './notifications.service';
import { NotificationsService } from './notifications.service';
export * from './notifications.serviceInterface';
export * from './programs.service';
import { ProgramsService } from './programs.service';
export * from './programs.serviceInterface';
export * from './rounds.service';
import { RoundsService } from './rounds.service';
export * from './rounds.serviceInterface';
export * from './sports.service';
import { SportsService } from './sports.service';
export * from './sports.serviceInterface';
export * from './teams.service';
import { TeamsService } from './teams.service';
export * from './teams.serviceInterface';
export const APIS = [AiService, AttachmentsService, AttendanceStatusesService, AuthService, EnergySegmentsService, EnergySystemsService, EventsService, ExercisesService, HealthService, InvitationsService, JoinMagicService, JoinRequestsService, LevelsService, MeService, MembersService, NotificationsService, ProgramsService, RoundsService, SportsService, TeamsService];
