/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { DashboardSummary } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface DashboardSummaryRetrieveRequestParams {
    today?: string;
}


export interface DashboardServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Aggregate dashboard payload (replaces the per-resource fan-out)
     * GET /api/v1/dashboard/summary/ — one-shot aggregate for the dashboard.
     * @endpoint get /api/v1/dashboard/summary/
* @param requestParameters
     */
    dashboardSummaryRetrieve(requestParameters: DashboardSummaryRetrieveRequestParams, extraHttpRequestParams?: any): Observable<DashboardSummary>;

}
