/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { EnergySegmentAdmin } from '../model/models';
import { PaginatedEnergySegmentList } from '../model/models';
import { PatchedEnergySegmentAdmin } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface EnergySegmentsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create energy segment (staff only)
     * CRUD on EnergySegment referential.
     * @endpoint post /api/v1/energy-segments/
     * @param energySegmentAdmin 
     */
    energySegmentsCreate(energySegmentAdmin: EnergySegmentAdmin, extraHttpRequestParams?: any): Observable<EnergySegmentAdmin>;

    /**
     * Soft delete energy segment (staff only)
     * CRUD on EnergySegment referential.
     * @endpoint delete /api/v1/energy-segments/{id}/
     * @param id A unique integer value identifying this energy segment.
     */
    energySegmentsDestroy(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * List energy segments (public flavor)
     * CRUD on EnergySegment referential.
     * @endpoint get /api/v1/energy-segments/
     * @param energysystem 
     * @param isActive 
     * @param ordering Which field to use when ordering the results.
     * @param page A page number within the paginated result set.
     * @param search A search term.
     */
    energySegmentsList(energysystem?: number, isActive?: boolean, ordering?: string, page?: number, search?: string, extraHttpRequestParams?: any): Observable<PaginatedEnergySegmentList>;

    /**
     * 
     * CRUD on EnergySegment referential.
     * @endpoint patch /api/v1/energy-segments/{id}/
     * @param id A unique integer value identifying this energy segment.
     * @param patchedEnergySegmentAdmin 
     */
    energySegmentsPartialUpdate(id: number, patchedEnergySegmentAdmin?: PatchedEnergySegmentAdmin, extraHttpRequestParams?: any): Observable<EnergySegmentAdmin>;

    /**
     * Retrieve energy segment (admin flavor for staff)
     * CRUD on EnergySegment referential.
     * @endpoint get /api/v1/energy-segments/{id}/
     * @param id A unique integer value identifying this energy segment.
     */
    energySegmentsRetrieve(id: number, extraHttpRequestParams?: any): Observable<EnergySegmentAdmin>;

    /**
     * 
     * CRUD on EnergySegment referential.
     * @endpoint put /api/v1/energy-segments/{id}/
     * @param id A unique integer value identifying this energy segment.
     * @param energySegmentAdmin 
     */
    energySegmentsUpdate(id: number, energySegmentAdmin: EnergySegmentAdmin, extraHttpRequestParams?: any): Observable<EnergySegmentAdmin>;

}
