/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Attendance } from '../model/models';
import { AttendanceBulkRequest } from '../model/models';
import { AttendanceRequest } from '../model/models';
import { DuplicateEventRequestRequest } from '../model/models';
import { DuplicateEventResponse } from '../model/models';
import { Event } from '../model/models';
import { EventDebrief } from '../model/models';
import { EventRequest } from '../model/models';
import { EventShareRequestRequest } from '../model/models';
import { EventShareResponse } from '../model/models';
import { EventTemplate } from '../model/models';
import { ExplainSessionResponse } from '../model/models';
import { GenerateTrainingRequestRequest } from '../model/models';
import { GenerateTrainingResponse } from '../model/models';
import { PaginatedAttendanceList } from '../model/models';
import { PaginatedEventList } from '../model/models';
import { PatchedAttendanceRequest } from '../model/models';
import { PatchedEventRequest } from '../model/models';
import { ReorderRoundsRequestRequest } from '../model/models';
import { RotiSummary } from '../model/models';
import { RotiUpsertRequest } from '../model/models';
import { RsvpApplyToAttendanceResult } from '../model/models';
import { RsvpSummary } from '../model/models';
import { RsvpUpsertRequest } from '../model/models';
import { SaveAsTemplateRequestRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface EventsAttendanceBulkCreateRequestParams {
    eventPk: number;
    attendanceBulkRequest: AttendanceBulkRequest;
}

export interface EventsAttendanceCreateRequestParams {
    eventPk: number;
    attendanceRequest: AttendanceRequest;
}

export interface EventsAttendanceDestroyRequestParams {
    eventPk: number;
    id: number;
}

export interface EventsAttendanceListRequestParams {
    eventPk: number;
    ordering?: string;
    page?: number;
    pageSize?: number;
    search?: string;
}

export interface EventsAttendancePartialUpdateRequestParams {
    eventPk: number;
    id: number;
    patchedAttendanceRequest?: PatchedAttendanceRequest;
}

export interface EventsAttendanceRetrieveRequestParams {
    eventPk: number;
    id: number;
}

export interface EventsAttendanceUpdateRequestParams {
    eventPk: number;
    id: number;
    attendanceRequest: AttendanceRequest;
}

export interface EventsCreateRequestParams {
    eventRequest: EventRequest;
}

export interface EventsDebriefRetrieveRequestParams {
    id: number;
}

export interface EventsDestroyRequestParams {
    id: number;
}

export interface EventsDuplicateCreateRequestParams {
    id: number;
    duplicateEventRequestRequest: DuplicateEventRequestRequest;
}

export interface EventsExplainCreateRequestParams {
    id: number;
}

export interface EventsGenerateTrainingCreateRequestParams {
    id: number;
    generateTrainingRequestRequest?: GenerateTrainingRequestRequest;
}

export interface EventsListRequestParams {
    color?: string;
    date?: string;
    dateGte?: string;
    dateLte?: string;
    ordering?: string;
    page?: number;
    pageSize?: number;
    referProgram?: number;
    referProgramIn?: Array<number>;
    search?: string;
}

export interface EventsPartialUpdateRequestParams {
    id: number;
    patchedEventRequest?: PatchedEventRequest;
}

export interface EventsRetrieveRequestParams {
    id: number;
}

export interface EventsRotiRetrieveRequestParams {
    eventPk: number;
}

export interface EventsRotiSummaryRequestParams {
    eventPk: number;
}

export interface EventsRotiUpdateRequestParams {
    eventPk: number;
    rotiUpsertRequest: RotiUpsertRequest;
}

export interface EventsRoundsReorderCreateRequestParams {
    id: number;
    reorderRoundsRequestRequest: ReorderRoundsRequestRequest;
}

export interface EventsRsvpApplyToAttendanceRequestParams {
    eventPk: number;
}

export interface EventsRsvpRetrieveRequestParams {
    eventPk: number;
}

export interface EventsRsvpUpdateRequestParams {
    eventPk: number;
    rsvpUpsertRequest: RsvpUpsertRequest;
}

export interface EventsSaveAsTemplateCreateRequestParams {
    id: number;
    saveAsTemplateRequestRequest: SaveAsTemplateRequestRequest;
}

export interface EventsShareCreateRequestParams {
    id: number;
    eventShareRequestRequest: EventShareRequestRequest;
}

export interface EventsUpdateRequestParams {
    id: number;
    eventRequest: EventRequest;
}


export interface EventsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Bulk set attendances for an event
     * Creates or updates multiple attendance rows in a single atomic call. For each item: if (event, member) exists, update status; otherwise, create new. Members not in the payload are NOT touched. All-or-nothing: any validation error rolls back the entire batch.
     * @endpoint post /api/v1/events/{event_pk}/attendance/bulk/
* @param requestParameters
     */
    eventsAttendanceBulkCreate(requestParameters: EventsAttendanceBulkCreateRequestParams, extraHttpRequestParams?: any): Observable<PaginatedAttendanceList>;

    /**
     * Create an attendance row (coach only)
     * Member must be in the team via an active TeamMembership. Returns 400 if a row already exists for (event, member) — use PATCH.
     * @endpoint post /api/v1/events/{event_pk}/attendance/
* @param requestParameters
     */
    eventsAttendanceCreate(requestParameters: EventsAttendanceCreateRequestParams, extraHttpRequestParams?: any): Observable<Attendance>;

    /**
     * Delete an attendance row (coach only)
     * CRUD on event attendance.  URL: /api/v1/events/{event_pk}/attendance/
     * @endpoint delete /api/v1/events/{event_pk}/attendance/{id}/
* @param requestParameters
     */
    eventsAttendanceDestroy(requestParameters: EventsAttendanceDestroyRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * List attendance for an event
     * Returns all attendance rows. Coaches see everyone; athletes see only their own row.
     * @endpoint get /api/v1/events/{event_pk}/attendance/
* @param requestParameters
     */
    eventsAttendanceList(requestParameters: EventsAttendanceListRequestParams, extraHttpRequestParams?: any): Observable<PaginatedAttendanceList>;

    /**
     * Update attendance status (coach only)
     * Update one or more fields of an attendance row. &#x60;member&#x60; is read-only after create and is silently ignored — to reassign attendance, DELETE the row and create a new one.
     * @endpoint patch /api/v1/events/{event_pk}/attendance/{id}/
* @param requestParameters
     */
    eventsAttendancePartialUpdate(requestParameters: EventsAttendancePartialUpdateRequestParams, extraHttpRequestParams?: any): Observable<Attendance>;

    /**
     * Retrieve a single attendance row
     * CRUD on event attendance.  URL: /api/v1/events/{event_pk}/attendance/
     * @endpoint get /api/v1/events/{event_pk}/attendance/{id}/
* @param requestParameters
     */
    eventsAttendanceRetrieve(requestParameters: EventsAttendanceRetrieveRequestParams, extraHttpRequestParams?: any): Observable<Attendance>;

    /**
     * Replace attendance row (coach only)
     * Replace an attendance row. &#x60;member&#x60; is read-only after create and is silently ignored on update — to reassign attendance, DELETE the row and create a new one.
     * @endpoint put /api/v1/events/{event_pk}/attendance/{id}/
* @param requestParameters
     */
    eventsAttendanceUpdate(requestParameters: EventsAttendanceUpdateRequestParams, extraHttpRequestParams?: any): Observable<Attendance>;

    /**
     * 
     * CRUD complet pour Event, scopé par team du program.
     * @endpoint post /api/v1/events/
* @param requestParameters
     */
    eventsCreate(requestParameters: EventsCreateRequestParams, extraHttpRequestParams?: any): Observable<Event>;

    /**
     * Consolidated post-session debrief (managers only)
     * One read with everything a coach reviews after a session: attendance (present/absent vs active roster), ROTI (average + count), RSVP (going/maybe/not_going/no_response) and the attachment count, plus the free-text &#x60;debrief&#x60; (edited via the normal event PATCH). Managers of the event\&#39;s team only.
     * @endpoint get /api/v1/events/{id}/debrief/
* @param requestParameters
     */
    eventsDebriefRetrieve(requestParameters: EventsDebriefRetrieveRequestParams, extraHttpRequestParams?: any): Observable<EventDebrief>;

    /**
     * 
     * CRUD complet pour Event, scopé par team du program.
     * @endpoint delete /api/v1/events/{id}/
* @param requestParameters
     */
    eventsDestroy(requestParameters: EventsDestroyRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * Duplicate this training session onto a new date, optionally repeating weekly. The copy deep-copies the source\&#39;s Rounds into fresh Round rows (re-linking the shared Exercise library) so each session is fully independent; per-session members are NOT copied. With &#x60;repeat_weekly&#x3D;true&#x60; and &#x60;occurrences&#x3D;N&#x60;, N sessions are created on &#x60;date&#x60;, &#x60;date&#x60;+7d, ..., &#x60;date&#x60;+7*(N-1)d. With &#x60;repeat_weekly&#x3D;false&#x60; exactly one copy is created (occurrences is forced to 1). Manager/owner of the event\&#39;s team only.
     * @endpoint post /api/v1/events/{id}/duplicate/
* @param requestParameters
     */
    eventsDuplicateCreate(requestParameters: EventsDuplicateCreateRequestParams, extraHttpRequestParams?: any): Observable<DuplicateEventResponse>;

    /**
     * 
     * Generate a short, plain-language brief of this session FOR THE ATHLETES and store it on the event (ai_athlete_brief). Managers of the event\&#39;s team only. The brief is shown to athletes only when they may see the goal (vis_goal). Throttled.
     * @endpoint post /api/v1/events/{id}/explain/
* @param requestParameters
     */
    eventsExplainCreate(requestParameters: EventsExplainCreateRequestParams, extraHttpRequestParams?: any): Observable<ExplainSessionResponse>;

    /**
     * 
     * Generate detailed Rounds and Exercises with AI for an Event. Optionally accepts an &#x60;additional_prompt&#x60; (max 2000 chars) appended to the LLM user prompt after the structured context.
     * @endpoint post /api/v1/events/{id}/generate-training/
* @param requestParameters
     */
    eventsGenerateTrainingCreate(requestParameters: EventsGenerateTrainingCreateRequestParams, extraHttpRequestParams?: any): Observable<GenerateTrainingResponse>;

    /**
     * 
     * CRUD complet pour Event, scopé par team du program.
     * @endpoint get /api/v1/events/
* @param requestParameters
     */
    eventsList(requestParameters: EventsListRequestParams, extraHttpRequestParams?: any): Observable<PaginatedEventList>;

    /**
     * 
     * CRUD complet pour Event, scopé par team du program.
     * @endpoint patch /api/v1/events/{id}/
* @param requestParameters
     */
    eventsPartialUpdate(requestParameters: EventsPartialUpdateRequestParams, extraHttpRequestParams?: any): Observable<Event>;

    /**
     * 
     * CRUD complet pour Event, scopé par team du program.
     * @endpoint get /api/v1/events/{id}/
* @param requestParameters
     */
    eventsRetrieve(requestParameters: EventsRetrieveRequestParams, extraHttpRequestParams?: any): Observable<Event>;

    /**
     * Get ROTI summary for an event (incl. my_score)
     * Returns the aggregate ROTI for the event (average, count, distribution) plus the caller\&#39;s own score (my_score). Coaches and athlete-members of the team may read.
     * @endpoint get /api/v1/events/{event_pk}/roti/
* @param requestParameters
     */
    eventsRotiRetrieve(requestParameters: EventsRotiRetrieveRequestParams, extraHttpRequestParams?: any): Observable<Array<RotiSummary>>;

    /**
     * ROTI aggregate summary for an event (managers)
     * Same shape as GET .../roti/. Provided as an explicit endpoint for the manager dashboard.
     * @endpoint get /api/v1/events/{event_pk}/roti/summary/
* @param requestParameters
     */
    eventsRotiSummary(requestParameters: EventsRotiSummaryRequestParams, extraHttpRequestParams?: any): Observable<RotiSummary>;

    /**
     * Upsert the caller\&#39;s own ROTI score (1..5)
     * Athlete-only: resolves the caller\&#39;s Member within the event\&#39;s team and update_or_creates their Roti(event, member) with the given score. Returns 403 if the team has roti_enabled&#x3D;False or the caller is not an athlete-member; 400 if the score is out of range.
     * @endpoint put /api/v1/events/{event_pk}/roti/
* @param requestParameters
     */
    eventsRotiUpdate(requestParameters: EventsRotiUpdateRequestParams, extraHttpRequestParams?: any): Observable<RotiSummary>;

    /**
     * 
     * Atomically reorder the Rounds attached to this Event. &#x60;round_ids&#x60; must contain exactly the IDs of the Rounds currently attached, in the desired final order. Round.order is set to 1..N matching list position, in a single transaction.
     * @endpoint post /api/v1/events/{id}/rounds/reorder/
* @param requestParameters
     */
    eventsRoundsReorderCreate(requestParameters: EventsRoundsReorderCreateRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Pre-fill attendance from RSVPs (managers only)
     * Managers/owner only. For each member with an RSVP on the event, upserts their Attendance: GOING -&gt; the \&#39;present\&#39; AttendanceStatus, NOT_GOING -&gt; \&#39;absent\&#39;. MAYBE is skipped (attendance left untouched). RSVPs whose target status code is not seeded are also skipped. Returns how many rows were applied and skipped.
     * @endpoint post /api/v1/events/{event_pk}/rsvp/apply_to_attendance/
* @param requestParameters
     */
    eventsRsvpApplyToAttendance(requestParameters: EventsRsvpApplyToAttendanceRequestParams, extraHttpRequestParams?: any): Observable<RsvpApplyToAttendanceResult>;

    /**
     * Get RSVP summary for an event (incl. my_status)
     * Returns the aggregate availability for the event (counts, total_members) plus the caller\&#39;s own status (my_status). Managers additionally get the per-member breakdown (by_member); athletes get an empty by_member. Coaches and athlete-members of the team may read.
     * @endpoint get /api/v1/events/{event_pk}/rsvp/
* @param requestParameters
     */
    eventsRsvpRetrieve(requestParameters: EventsRsvpRetrieveRequestParams, extraHttpRequestParams?: any): Observable<RsvpSummary>;

    /**
     * Upsert the caller\&#39;s own RSVP (going/maybe/not_going)
     * Athlete-only: resolves the caller\&#39;s Member within the event\&#39;s team and update_or_creates their Rsvp(event, member) with the given status. Returns 403 if the team has rsvp_enabled&#x3D;False or the caller is not an athlete-member; 400 if the status is invalid.
     * @endpoint put /api/v1/events/{event_pk}/rsvp/
* @param requestParameters
     */
    eventsRsvpUpdate(requestParameters: EventsRsvpUpdateRequestParams, extraHttpRequestParams?: any): Observable<RsvpSummary>;

    /**
     * 
     * Save this session as a reusable team template (managers only). Copies goal/total/sport and deep-copies the rounds; the template is independent of later edits to this event.
     * @endpoint post /api/v1/events/{id}/save-as-template/
* @param requestParameters
     */
    eventsSaveAsTemplateCreate(requestParameters: EventsSaveAsTemplateCreateRequestParams, extraHttpRequestParams?: any): Observable<EventTemplate>;

    /**
     * 
     * Toggle the public read-only share link for this session. Enabling (is_public&#x3D;true) requires the event\&#39;s team to have public_sharing_enabled&#x3D;true (else 409 public_sharing_disabled) and mints an unguessable token if absent. Disabling (is_public&#x3D;false) keeps the token so re-enabling reuses the same URL. Manager/owner of the event\&#39;s team only.
     * @endpoint post /api/v1/events/{id}/share/
* @param requestParameters
     */
    eventsShareCreate(requestParameters: EventsShareCreateRequestParams, extraHttpRequestParams?: any): Observable<EventShareResponse>;

    /**
     * 
     * CRUD complet pour Event, scopé par team du program.
     * @endpoint put /api/v1/events/{id}/
* @param requestParameters
     */
    eventsUpdate(requestParameters: EventsUpdateRequestParams, extraHttpRequestParams?: any): Observable<Event>;

}
