/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Event } from '../model/models';
import { EventTemplate } from '../model/models';
import { InstantiateTemplateRequestRequest } from '../model/models';
import { PaginatedEventTemplateList } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface EventTemplatesDestroyRequestParams {
    id: number;
}

export interface EventTemplatesInstantiateCreateRequestParams {
    id: number;
    instantiateTemplateRequestRequest: InstantiateTemplateRequestRequest;
}

export interface EventTemplatesListRequestParams {
    ordering?: string;
    page?: number;
    pageSize?: number;
    search?: string;
}

export interface EventTemplatesRetrieveRequestParams {
    id: number;
}


export interface EventTemplatesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * Reusable session templates, scoped to teams the caller manages.  URL: /api/v1/event-templates/ - GET (list, optional ?team&#x3D;): the caller\&#39;s managed teams\&#39; templates. - DELETE /{id}/: remove a template (manager of its team). - POST /{id}/instantiate/ {refer_program, date}: create an Event from it.
     * @endpoint post /api/v1/event-templates/
*/
    eventTemplatesCreate(extraHttpRequestParams?: any): Observable<EventTemplate>;

    /**
     * 
     * Reusable session templates, scoped to teams the caller manages.  URL: /api/v1/event-templates/ - GET (list, optional ?team&#x3D;): the caller\&#39;s managed teams\&#39; templates. - DELETE /{id}/: remove a template (manager of its team). - POST /{id}/instantiate/ {refer_program, date}: create an Event from it.
     * @endpoint delete /api/v1/event-templates/{id}/
* @param requestParameters
     */
    eventTemplatesDestroy(requestParameters: EventTemplatesDestroyRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * Create a new Event from this template onto the given program + date (manager of the template\&#39;s team only). Deep-copies the template\&#39;s rounds.
     * @endpoint post /api/v1/event-templates/{id}/instantiate/
* @param requestParameters
     */
    eventTemplatesInstantiateCreate(requestParameters: EventTemplatesInstantiateCreateRequestParams, extraHttpRequestParams?: any): Observable<Event>;

    /**
     * 
     * Reusable session templates, scoped to teams the caller manages.  URL: /api/v1/event-templates/ - GET (list, optional ?team&#x3D;): the caller\&#39;s managed teams\&#39; templates. - DELETE /{id}/: remove a template (manager of its team). - POST /{id}/instantiate/ {refer_program, date}: create an Event from it.
     * @endpoint get /api/v1/event-templates/
* @param requestParameters
     */
    eventTemplatesList(requestParameters: EventTemplatesListRequestParams, extraHttpRequestParams?: any): Observable<PaginatedEventTemplateList>;

    /**
     * 
     * Reusable session templates, scoped to teams the caller manages.  URL: /api/v1/event-templates/ - GET (list, optional ?team&#x3D;): the caller\&#39;s managed teams\&#39; templates. - DELETE /{id}/: remove a template (manager of its team). - POST /{id}/instantiate/ {refer_program, date}: create an Event from it.
     * @endpoint get /api/v1/event-templates/{id}/
* @param requestParameters
     */
    eventTemplatesRetrieve(requestParameters: EventTemplatesRetrieveRequestParams, extraHttpRequestParams?: any): Observable<EventTemplate>;

}
