/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CompleteInvitation } from '../model/models';
import { CompleteInvitationResponse } from '../model/models';
import { CreateInvitation } from '../model/models';
import { PaginatedTeamInvitationList } from '../model/models';
import { TeamInvitation } from '../model/models';
import { ValidateInvitation } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface InvitationsCreateRequestParams {
    createInvitation: CreateInvitation;
}

export interface InvitationsDestroyRequestParams {
    id: number;
}

export interface InvitationsListRequestParams {
    ordering?: string;
    page?: number;
    pageSize?: number;
    search?: string;
    status?: 'cancelled' | 'completed' | 'expired' | 'pending';
    team?: number;
}

export interface InvitationsLookupCreateRequestParams {
    token: string;
    completeInvitation: CompleteInvitation;
}

export interface InvitationsLookupRetrieveRequestParams {
    token: string;
}

export interface InvitationsRetrieveRequestParams {
    id: number;
}


export interface InvitationsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * Trainer pre-registers an athlete on a managed team by sending an invitation email. Refused with code&#x3D;user_already_registered if the email matches an existing user account; the trainer must use a different flow (e.g. ask the user to issue a TeamJoinRequest) for registered users.
     * @endpoint post /api/v1/invitations/
* @param requestParameters
     */
    invitationsCreate(requestParameters: InvitationsCreateRequestParams, extraHttpRequestParams?: any): Observable<TeamInvitation>;

    /**
     * 
     * Trainer invitation flow.
     * @endpoint delete /api/v1/invitations/{id}/
* @param requestParameters
     */
    invitationsDestroy(requestParameters: InvitationsDestroyRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * Trainer invitation flow.
     * @endpoint get /api/v1/invitations/
* @param requestParameters
     */
    invitationsList(requestParameters: InvitationsListRequestParams, extraHttpRequestParams?: any): Observable<PaginatedTeamInvitationList>;

    /**
     * 
     * Finalize invitation: create the user, link Member, return JWT.
     * @endpoint post /api/v1/invitations/lookup/{token}/
* @param requestParameters
     */
    invitationsLookupCreate(requestParameters: InvitationsLookupCreateRequestParams, extraHttpRequestParams?: any): Observable<CompleteInvitationResponse>;

    /**
     * 
     * Lookup an invitation by token. No authentication required.
     * @endpoint get /api/v1/invitations/lookup/{token}/
* @param requestParameters
     */
    invitationsLookupRetrieve(requestParameters: InvitationsLookupRetrieveRequestParams, extraHttpRequestParams?: any): Observable<ValidateInvitation>;

    /**
     * 
     * Trainer invitation flow.
     * @endpoint get /api/v1/invitations/{id}/
* @param requestParameters
     */
    invitationsRetrieve(requestParameters: InvitationsRetrieveRequestParams, extraHttpRequestParams?: any): Observable<TeamInvitation>;

}
