/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateJoinRequest } from '../model/models';
import { PaginatedTeamJoinRequestList } from '../model/models';
import { PatchedTeamJoinRequest } from '../model/models';
import { TeamJoinRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface JoinRequestsCreateRequestParams {
    createJoinRequest: CreateJoinRequest;
}

export interface JoinRequestsDestroyRequestParams {
    id: number;
}

export interface JoinRequestsListRequestParams {
    ordering?: string;
    page?: number;
    pageSize?: number;
    search?: string;
    status?: 'accepted' | 'cancelled' | 'pending' | 'rejected';
    team?: number;
}

export interface JoinRequestsPartialUpdateRequestParams {
    id: number;
    patchedTeamJoinRequest?: PatchedTeamJoinRequest;
}

export interface JoinRequestsRetrieveRequestParams {
    id: number;
}

export interface JoinRequestsUpdateRequestParams {
    id: number;
    teamJoinRequest: TeamJoinRequest;
}


export interface JoinRequestsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * Self-signup join request flow.
     * @endpoint post /api/v1/join-requests/
* @param requestParameters
     */
    joinRequestsCreate(requestParameters: JoinRequestsCreateRequestParams, extraHttpRequestParams?: any): Observable<CreateJoinRequest>;

    /**
     * 
     * Self-signup join request flow.
     * @endpoint delete /api/v1/join-requests/{id}/
* @param requestParameters
     */
    joinRequestsDestroy(requestParameters: JoinRequestsDestroyRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * Self-signup join request flow.
     * @endpoint get /api/v1/join-requests/
* @param requestParameters
     */
    joinRequestsList(requestParameters: JoinRequestsListRequestParams, extraHttpRequestParams?: any): Observable<PaginatedTeamJoinRequestList>;

    /**
     * 
     * Self-signup join request flow.
     * @endpoint patch /api/v1/join-requests/{id}/
* @param requestParameters
     */
    joinRequestsPartialUpdate(requestParameters: JoinRequestsPartialUpdateRequestParams, extraHttpRequestParams?: any): Observable<TeamJoinRequest>;

    /**
     * 
     * Self-signup join request flow.
     * @endpoint get /api/v1/join-requests/{id}/
* @param requestParameters
     */
    joinRequestsRetrieve(requestParameters: JoinRequestsRetrieveRequestParams, extraHttpRequestParams?: any): Observable<TeamJoinRequest>;

    /**
     * 
     * Self-signup join request flow.
     * @endpoint put /api/v1/join-requests/{id}/
* @param requestParameters
     */
    joinRequestsUpdate(requestParameters: JoinRequestsUpdateRequestParams, extraHttpRequestParams?: any): Observable<TeamJoinRequest>;

}
