/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { LevelAdmin } from '../model/models';
import { LevelAdminRequest } from '../model/models';
import { PaginatedLevelList } from '../model/models';
import { PatchedLevelAdminRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface LevelsCreateRequestParams {
    levelAdminRequest: LevelAdminRequest;
}

export interface LevelsDestroyRequestParams {
    id: number;
}

export interface LevelsListRequestParams {
    includeInactive?: boolean;
    isActive?: boolean;
    ordering?: string;
    page?: number;
    pageSize?: number;
    search?: string;
}

export interface LevelsPartialUpdateRequestParams {
    id: number;
    includeInactive?: boolean;
    patchedLevelAdminRequest?: PatchedLevelAdminRequest;
}

export interface LevelsRetrieveRequestParams {
    id: number;
    includeInactive?: boolean;
}

export interface LevelsUpdateRequestParams {
    id: number;
    levelAdminRequest: LevelAdminRequest;
    includeInactive?: boolean;
}


export interface LevelsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create level (staff only)
     * Accepts the admin flavor with name_*_/description_* variants.
     * @endpoint post /api/v1/levels/
* @param requestParameters
     */
    levelsCreate(requestParameters: LevelsCreateRequestParams, extraHttpRequestParams?: any): Observable<LevelAdmin>;

    /**
     * Soft delete level (staff only)
     * Sets is_active&#x3D;False; does not hard delete.
     * @endpoint delete /api/v1/levels/{id}/
* @param requestParameters
     */
    levelsDestroy(requestParameters: LevelsDestroyRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * List levels (public flavor)
     * Returns the public Level serializer with localized \&#39;name\&#39; and \&#39;description\&#39;. Available to all authenticated users. Pass ?include_inactive&#x3D;true (staff only) to include soft-deleted rows.
     * @endpoint get /api/v1/levels/
* @param requestParameters
     */
    levelsList(requestParameters: LevelsListRequestParams, extraHttpRequestParams?: any): Observable<PaginatedLevelList>;

    /**
     * 
     * CRUD on the Level referential.  Read: any authenticated user (default queryset filters is_active&#x3D;True). Write: staff only. Soft delete bumps updated_at.
     * @endpoint patch /api/v1/levels/{id}/
* @param requestParameters
     */
    levelsPartialUpdate(requestParameters: LevelsPartialUpdateRequestParams, extraHttpRequestParams?: any): Observable<LevelAdmin>;

    /**
     * Retrieve level (admin flavor for staff)
     * Returns the admin flavor with name_*_/description_* per-language variants when called by a staff user, otherwise the public flavor.
     * @endpoint get /api/v1/levels/{id}/
* @param requestParameters
     */
    levelsRetrieve(requestParameters: LevelsRetrieveRequestParams, extraHttpRequestParams?: any): Observable<LevelAdmin>;

    /**
     * 
     * CRUD on the Level referential.  Read: any authenticated user (default queryset filters is_active&#x3D;True). Write: staff only. Soft delete bumps updated_at.
     * @endpoint put /api/v1/levels/{id}/
* @param requestParameters
     */
    levelsUpdate(requestParameters: LevelsUpdateRequestParams, extraHttpRequestParams?: any): Observable<LevelAdmin>;

}
