/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PaginatedPlaceList } from '../model/models';
import { PatchedPlace } from '../model/models';
import { Place } from '../model/models';
import { PlaceRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PlacesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a place (manager only)
     * Create a managed venue for a team. The requester must own or manage the team. A duplicate (team, name) returns 400 with code &#x60;place_already_exists&#x60;.
     * @endpoint post /api/v1/places/
     * @param placeRequest 
     */
    placesCreate(placeRequest: PlaceRequest, extraHttpRequestParams?: any): Observable<Place>;

    /**
     * Delete a place (manager only)
     * Hard-deletes the venue. Events referencing it keep their free-text &#x60;location&#x60; (their &#x60;place&#x60; FK is SET_NULL).
     * @endpoint delete /api/v1/places/{id}/
     * @param id A unique integer value identifying this place.
     */
    placesDestroy(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * List managed places (Lieux) of a team
     * Returns the team\&#39;s managed venues, ordered by name. Scoped to the teams the requester is a strict member of (owner/manager/active athlete). Pass ?team&#x3D;&lt;id&gt; to filter to a single team; without it, places across all the requester\&#39;s member teams are returned.
     * @endpoint get /api/v1/places/
     * @param ordering Which field to use when ordering the results.
     * @param page A page number within the paginated result set.
     * @param pageSize Number of results to return per page.
     * @param search A search term.
     * @param team Restrict to one team the requester is a member of.
     */
    placesList(ordering?: string, page?: number, pageSize?: number, search?: string, team?: number, extraHttpRequestParams?: any): Observable<PaginatedPlaceList>;

    /**
     * Patch a place (manager only)
     * CRUD on the managed team venue (Lieu).  Read: any strict member of the place\&#39;s team. Write (create/update/delete): owner or manager of the team only.
     * @endpoint patch /api/v1/places/{id}/
     * @param id A unique integer value identifying this place.
     * @param patchedPlace 
     */
    placesPartialUpdate(id: number, patchedPlace?: PatchedPlace, extraHttpRequestParams?: any): Observable<Place>;

    /**
     * Retrieve a place
     * CRUD on the managed team venue (Lieu).  Read: any strict member of the place\&#39;s team. Write (create/update/delete): owner or manager of the team only.
     * @endpoint get /api/v1/places/{id}/
     * @param id A unique integer value identifying this place.
     */
    placesRetrieve(id: number, extraHttpRequestParams?: any): Observable<Place>;

    /**
     * Update a place (manager only)
     * CRUD on the managed team venue (Lieu).  Read: any strict member of the place\&#39;s team. Write (create/update/delete): owner or manager of the team only.
     * @endpoint put /api/v1/places/{id}/
     * @param id A unique integer value identifying this place.
     * @param placeRequest 
     */
    placesUpdate(id: number, placeRequest: PlaceRequest, extraHttpRequestParams?: any): Observable<Place>;

}
