/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PaginatedPlaceList } from '../model/models';
import { PatchedPlace } from '../model/models';
import { Place } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface PlacesCreateRequestParams {
    place: Place;
}

export interface PlacesDestroyRequestParams {
    id: number;
}

export interface PlacesListRequestParams {
    ordering?: string;
    page?: number;
    pageSize?: number;
    search?: string;
    sport?: number;
    team?: number;
}

export interface PlacesPartialUpdateRequestParams {
    id: number;
    patchedPlace?: PatchedPlace;
}

export interface PlacesRetrieveRequestParams {
    id: number;
}

export interface PlacesUpdateRequestParams {
    id: number;
    place: Place;
}


export interface PlacesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a place and link it to a team (manager only)
     * Creates a venue in the pool and links it to the given team (the requester must manage that team); the place\&#39;s sport is the team\&#39;s sport.
     * @endpoint post /api/v1/places/
* @param requestParameters
     */
    placesCreate(requestParameters: PlacesCreateRequestParams, extraHttpRequestParams?: any): Observable<Place>;

    /**
     * Delete a place (manager of a linked team)
     * Hard-deletes the venue across all teams that linked it. Events referencing it keep their free-text location (place FK is SET_NULL).
     * @endpoint delete /api/v1/places/{id}/
* @param requestParameters
     */
    placesDestroy(requestParameters: PlacesDestroyRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * List venues (Lieux) from the sport pool
     * Returns venues from the global, sport-scoped pool. ?team&#x3D;&lt;id&gt; restricts to a team\&#39;s linked places (members only); ?sport&#x3D;&lt;id&gt; returns the whole pool for a sport (to attach/share). Without filters, returns places linked to the requester\&#39;s member teams.
     * @endpoint get /api/v1/places/
* @param requestParameters
     */
    placesList(requestParameters: PlacesListRequestParams, extraHttpRequestParams?: any): Observable<PaginatedPlaceList>;

    /**
     * Patch a place (manager of a linked team)
     * CRUD on the shared, sport-scoped venue pool (Lieu).  Read: members see places linked to their teams, or a whole sport\&#39;s pool via ?sport. Write: create links a new place to a team the requester manages; update/delete require managing a team the place is linked to.
     * @endpoint patch /api/v1/places/{id}/
* @param requestParameters
     */
    placesPartialUpdate(requestParameters: PlacesPartialUpdateRequestParams, extraHttpRequestParams?: any): Observable<Place>;

    /**
     * Retrieve a place
     * CRUD on the shared, sport-scoped venue pool (Lieu).  Read: members see places linked to their teams, or a whole sport\&#39;s pool via ?sport. Write: create links a new place to a team the requester manages; update/delete require managing a team the place is linked to.
     * @endpoint get /api/v1/places/{id}/
* @param requestParameters
     */
    placesRetrieve(requestParameters: PlacesRetrieveRequestParams, extraHttpRequestParams?: any): Observable<Place>;

    /**
     * Update a place (manager of a linked team)
     * CRUD on the shared, sport-scoped venue pool (Lieu).  Read: members see places linked to their teams, or a whole sport\&#39;s pool via ?sport. Write: create links a new place to a team the requester manages; update/delete require managing a team the place is linked to.
     * @endpoint put /api/v1/places/{id}/
* @param requestParameters
     */
    placesUpdate(requestParameters: PlacesUpdateRequestParams, extraHttpRequestParams?: any): Observable<Place>;

}
