/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GeneratePlanRequest } from '../model/models';
import { GeneratePlanResponse } from '../model/models';
import { PaginatedProgramList } from '../model/models';
import { PatchedProgram } from '../model/models';
import { Program } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ProgramsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * CRUD complet pour Program, scopé par team.
     * @endpoint post /api/v1/programs/
     * @param program 
     */
    programsCreate(program: Program, extraHttpRequestParams?: any): Observable<Program>;

    /**
     * 
     * CRUD complet pour Program, scopé par team.
     * @endpoint delete /api/v1/programs/{id}/
     * @param id A unique integer value identifying this Program.
     */
    programsDestroy(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * Generate a training plan with AI for the given Program.
     * @endpoint post /api/v1/programs/{id}/generate-events/
     * @param id A unique integer value identifying this Program.
     * @param generatePlanRequest 
     */
    programsGenerateEventsCreate(id: number, generatePlanRequest: GeneratePlanRequest, extraHttpRequestParams?: any): Observable<GeneratePlanResponse>;

    /**
     * 
     * CRUD complet pour Program, scopé par team.
     * @endpoint get /api/v1/programs/
     * @param dateEnd 
     * @param dateStart 
     * @param name 
     * @param ordering Which field to use when ordering the results.
     * @param page A page number within the paginated result set.
     * @param search A search term.
     * @param team 
     */
    programsList(dateEnd?: string, dateStart?: string, name?: string, ordering?: string, page?: number, search?: string, team?: number, extraHttpRequestParams?: any): Observable<PaginatedProgramList>;

    /**
     * 
     * CRUD complet pour Program, scopé par team.
     * @endpoint patch /api/v1/programs/{id}/
     * @param id A unique integer value identifying this Program.
     * @param patchedProgram 
     */
    programsPartialUpdate(id: number, patchedProgram?: PatchedProgram, extraHttpRequestParams?: any): Observable<Program>;

    /**
     * 
     * CRUD complet pour Program, scopé par team.
     * @endpoint get /api/v1/programs/{id}/
     * @param id A unique integer value identifying this Program.
     */
    programsRetrieve(id: number, extraHttpRequestParams?: any): Observable<Program>;

    /**
     * 
     * CRUD complet pour Program, scopé par team.
     * @endpoint put /api/v1/programs/{id}/
     * @param id A unique integer value identifying this Program.
     * @param program 
     */
    programsUpdate(id: number, program: Program, extraHttpRequestParams?: any): Observable<Program>;

}
