/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GeneratePlanRequestRequest } from '../model/models';
import { GeneratePlanResponse } from '../model/models';
import { PaginatedProgramList } from '../model/models';
import { PatchedProgramRequest } from '../model/models';
import { Program } from '../model/models';
import { ProgramRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ProgramsCreateRequestParams {
    programRequest: ProgramRequest;
}

export interface ProgramsDestroyRequestParams {
    id: number;
}

export interface ProgramsGenerateEventsCreateRequestParams {
    id: number;
    generatePlanRequestRequest: GeneratePlanRequestRequest;
}

export interface ProgramsListRequestParams {
    dateEnd?: string;
    dateStart?: string;
    includeInactive?: boolean;
    isActive?: boolean;
    name?: string;
    ordering?: string;
    page?: number;
    pageSize?: number;
    search?: string;
    team?: number;
}

export interface ProgramsPartialUpdateRequestParams {
    id: number;
    includeInactive?: boolean;
    patchedProgramRequest?: PatchedProgramRequest;
}

export interface ProgramsRetrieveRequestParams {
    id: number;
    includeInactive?: boolean;
}

export interface ProgramsUpdateRequestParams {
    id: number;
    programRequest: ProgramRequest;
    includeInactive?: boolean;
}


export interface ProgramsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * CRUD complet pour Program, scopé par team.  Soft-delete convention: DELETE flips is_active&#x3D;False (no hard delete). Default queryset hides is_active&#x3D;False. ?include_inactive&#x3D;true is honored for staff (sees all inactives across visible teams) and for managers (sees inactives of teams they manage).
     * @endpoint post /api/v1/programs/
* @param requestParameters
     */
    programsCreate(requestParameters: ProgramsCreateRequestParams, extraHttpRequestParams?: any): Observable<Program>;

    /**
     * Soft delete program (manager of team only)
     * Sets is_active&#x3D;False; does not hard delete.
     * @endpoint delete /api/v1/programs/{id}/
* @param requestParameters
     */
    programsDestroy(requestParameters: ProgramsDestroyRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * Generate a training plan with AI for the given Program.
     * @endpoint post /api/v1/programs/{id}/generate-events/
* @param requestParameters
     */
    programsGenerateEventsCreate(requestParameters: ProgramsGenerateEventsCreateRequestParams, extraHttpRequestParams?: any): Observable<GeneratePlanResponse>;

    /**
     * 
     * CRUD complet pour Program, scopé par team.  Soft-delete convention: DELETE flips is_active&#x3D;False (no hard delete). Default queryset hides is_active&#x3D;False. ?include_inactive&#x3D;true is honored for staff (sees all inactives across visible teams) and for managers (sees inactives of teams they manage).
     * @endpoint get /api/v1/programs/
* @param requestParameters
     */
    programsList(requestParameters: ProgramsListRequestParams, extraHttpRequestParams?: any): Observable<PaginatedProgramList>;

    /**
     * 
     * CRUD complet pour Program, scopé par team.  Soft-delete convention: DELETE flips is_active&#x3D;False (no hard delete). Default queryset hides is_active&#x3D;False. ?include_inactive&#x3D;true is honored for staff (sees all inactives across visible teams) and for managers (sees inactives of teams they manage).
     * @endpoint patch /api/v1/programs/{id}/
* @param requestParameters
     */
    programsPartialUpdate(requestParameters: ProgramsPartialUpdateRequestParams, extraHttpRequestParams?: any): Observable<Program>;

    /**
     * 
     * CRUD complet pour Program, scopé par team.  Soft-delete convention: DELETE flips is_active&#x3D;False (no hard delete). Default queryset hides is_active&#x3D;False. ?include_inactive&#x3D;true is honored for staff (sees all inactives across visible teams) and for managers (sees inactives of teams they manage).
     * @endpoint get /api/v1/programs/{id}/
* @param requestParameters
     */
    programsRetrieve(requestParameters: ProgramsRetrieveRequestParams, extraHttpRequestParams?: any): Observable<Program>;

    /**
     * 
     * CRUD complet pour Program, scopé par team.  Soft-delete convention: DELETE flips is_active&#x3D;False (no hard delete). Default queryset hides is_active&#x3D;False. ?include_inactive&#x3D;true is honored for staff (sees all inactives across visible teams) and for managers (sees inactives of teams they manage).
     * @endpoint put /api/v1/programs/{id}/
* @param requestParameters
     */
    programsUpdate(requestParameters: ProgramsUpdateRequestParams, extraHttpRequestParams?: any): Observable<Program>;

}
