/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PaginatedTeamList } from '../model/models';
import { PatchedTeam } from '../model/models';
import { Team } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TeamsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * CRUD sur Teams. Liste &#x3D; teams gérées par l\&#39;user + teams publiques actives.
     * @endpoint post /api/v1/teams/
     * @param team 
     */
    teamsCreate(team: Team, extraHttpRequestParams?: any): Observable<Team>;

    /**
     * 
     * CRUD sur Teams. Liste &#x3D; teams gérées par l\&#39;user + teams publiques actives.
     * @endpoint delete /api/v1/teams/{id}/
     * @param id Un(une) valeur entière unique identifiant ce(cette) team.
     */
    teamsDestroy(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * CRUD sur Teams. Liste &#x3D; teams gérées par l\&#39;user + teams publiques actives.
     * @endpoint get /api/v1/teams/
     * @param isActive 
     * @param isPublic 
     * @param language * &#x60;fr&#x60; - Français * &#x60;nl&#x60; - Nederlands * &#x60;en&#x60; - English * &#x60;it&#x60; - Italiano * &#x60;es&#x60; - Español
     * @param ordering Quel champ utiliser pour classer les résultats.
     * @param page Un numéro de page de l\&#39;ensemble des résultats.
     * @param search Un terme de recherche.
     */
    teamsList(isActive?: boolean, isPublic?: boolean, language?: 'en' | 'es' | 'fr' | 'it' | 'nl', ordering?: string, page?: number, search?: string, extraHttpRequestParams?: any): Observable<PaginatedTeamList>;

    /**
     * 
     * CRUD sur Teams. Liste &#x3D; teams gérées par l\&#39;user + teams publiques actives.
     * @endpoint patch /api/v1/teams/{id}/
     * @param id Un(une) valeur entière unique identifiant ce(cette) team.
     * @param patchedTeam 
     */
    teamsPartialUpdate(id: number, patchedTeam?: PatchedTeam, extraHttpRequestParams?: any): Observable<Team>;

    /**
     * 
     * CRUD sur Teams. Liste &#x3D; teams gérées par l\&#39;user + teams publiques actives.
     * @endpoint get /api/v1/teams/{id}/
     * @param id Un(une) valeur entière unique identifiant ce(cette) team.
     */
    teamsRetrieve(id: number, extraHttpRequestParams?: any): Observable<Team>;

    /**
     * 
     * CRUD sur Teams. Liste &#x3D; teams gérées par l\&#39;user + teams publiques actives.
     * @endpoint put /api/v1/teams/{id}/
     * @param id Un(une) valeur entière unique identifiant ce(cette) team.
     * @param team 
     */
    teamsUpdate(id: number, team: Team, extraHttpRequestParams?: any): Observable<Team>;

}
