/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `member_anonymized` - Member anonymized * `member_removed` - Member removed from team * `account_deleted` - Account deleted * `session_shared` - Session shared publicly * `session_unshared` - Session sharing disabled * `attachment_deleted` - Attachment deleted * `team_config_updated` - Team configuration updated
 */
export enum ActionEnum {

    MemberAnonymized = 'member_anonymized',

    MemberRemoved = 'member_removed',

    AccountDeleted = 'account_deleted',

    SessionShared = 'session_shared',

    SessionUnshared = 'session_unshared',

    AttachmentDeleted = 'attachment_deleted',

    TeamConfigUpdated = 'team_config_updated'
}

