/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AIPingRequest { 
    /**
     * Prompt to send to Claude. Defaults to a hello-world prompt.
     */
    prompt?: string;
}

