/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `pending` - pending * `ready` - ready
 */
export enum AttachmentStatusEnum {

    Pending = 'pending',

    Ready = 'ready'
}

