/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttendanceBulkItem } from './attendance-bulk-item';


export interface AttendanceBulk { 
    attendances: Array<AttendanceBulkItem>;
}

