/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateInvitation { 
    team: number;
    email: string;
    firstname: string;
    lastname: string;
    phonenumber?: string;
}

