/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Public user payload for nested read contexts.  Excludes email and other privacy-sensitive fields. Use this whenever a user is exposed inside another resource (Team.owner, Member.user, TeamInvitation.invited_by, ...).
 */
export interface CustomUserPublic { 
    readonly id: number;
    /**
     * Requis. 150 caractères maximum. Uniquement des lettres, nombres et les caractères « @ », « . », « + », « - » et « _ ».
     */
    readonly username: string;
    readonly first_name: string;
    readonly last_name: string;
}

