/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlaceMinimal } from './place-minimal';


/**
 * The minimal Event shape the dashboard lists render.
 */
export interface DashboardEvent { 
    id: number;
    name: string;
    date: string | null;
    hour_start: string | null;
    hour_end: string | null;
    location: string;
    place: PlaceMinimal | null;
}

