/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DashboardMemberTeam } from './dashboard-member-team';
import { DashboardHistoryItem } from './dashboard-history-item';
import { DashboardEventItem } from './dashboard-event-item';
import { DashboardManagedTeam } from './dashboard-managed-team';


/**
 * Top-level aggregate payload for GET /dashboard/summary/.
 */
export interface DashboardSummary { 
    coach_teams: Array<DashboardManagedTeam>;
    member_teams: Array<DashboardMemberTeam>;
    coach_upcoming: Array<DashboardEventItem>;
    coach_upcoming_total: number;
    coach_attendance_pending: Array<DashboardEventItem>;
    coach_pending_truncated: boolean;
    member_upcoming: Array<DashboardEventItem>;
    member_upcoming_total: number;
    member_attendance_history: Array<DashboardHistoryItem>;
    member_history_truncated: boolean;
}

