/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DebriefAttendance { 
    present: number;
    absent: number;
    /**
     * Active athlete members of the team.
     */
    total: number;
}

