/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlatformEnum } from './platform-enum';


export interface DeviceRegisterRequest { 
    push_token: string;
    platform: PlatformEnum;
    device_name?: string;
}



