/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `email_changed` - email_changed
 */
export enum EmailChangeConfirmResponseCodeEnum {

    EmailChanged = 'email_changed'
}

