/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `ping` - Ping * `plan` - Generate plan * `training` - Generate training * `training_freeform` - Generate free-text training * `review` - Review training block * `explain` - Explain session for athletes
 */
export enum EndpointEnum {

    Ping = 'ping',

    Plan = 'plan',

    Training = 'training',

    TrainingFreeform = 'training_freeform',

    Review = 'review',

    Explain = 'explain'
}

