/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Admin flavor: per-language description variants + writable energy_system_id.
 */
export interface EnergySegmentAdminRequest { 
    abv: string;
    description_fr?: string | null;
    description_nl?: string | null;
    description_en?: string | null;
    description_it?: string | null;
    description_es?: string | null;
    energy_system_id: number;
    is_active?: boolean;
}

