/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Compact nested read shape for Event.equipment_items.
 */
export interface EquipmentMinimal { 
    readonly id: number;
    /**
     * Display name of the equipment (e.g. \'Pull-buoy\').
     */
    readonly name: string;
}

