/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProgramMinimal } from './program-minimal';


export interface Event { 
    readonly id: number;
    name: string;
    goal?: string | null;
    color?: string;
    date?: string | null;
    hour_start?: string | null;
    hour_end?: string | null;
    total?: number;
    readonly refer_program: ProgramMinimal;
    refer_program_id: number;
    rounds?: Array<number>;
    readonly members: Array<number>;
    readonly generated_by_ai: boolean;
    readonly ai_response: string;
    readonly ai_generated_at: string | null;
    readonly created_at: string;
    readonly updated_at: string;
}

