/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EquipmentMinimal } from './equipment-minimal';
import { Sport } from './sport';
import { TrainingTypeEnum } from './training-type-enum';
import { VisibilityMode } from './visibility-mode';
import { PlaceMinimal } from './place-minimal';
import { EventRoundDetail } from './event-round-detail';
import { ProgramMinimal } from './program-minimal';


export interface Event { 
    readonly id: number;
    name: string;
    goal?: string | null;
    /**
     * This event\'s active training-content type. Seeded at creation from the team-sport / sport cascade; editable by the coach.  * `structured` - Structured (rounds & exercises) * `freeform` - Free text
     */
    training_type?: TrainingTypeEnum;
    /**
     * Free-text training content (sanitized HTML) when training_type=freeform.
     */
    training_richtext?: string;
    /**
     * Where the session takes place (venue, pool, track, address). Always visible to athletes.
     */
    location?: string;
    readonly place: PlaceMinimal | null;
    /**
     * Material/gear athletes should bring. Always visible to athletes.
     */
    equipment?: string;
    readonly equipment_items: Array<EquipmentMinimal>;
    color?: string;
    date?: string | null;
    hour_start?: string | null;
    hour_end?: string | null;
    total?: number;
    readonly refer_program: ProgramMinimal;
    readonly team_id: number;
    readonly sport: Sport;
    readonly rounds: Array<number>;
    readonly rounds_detail: Array<EventRoundDetail>;
    readonly members: Array<number>;
    /**
     * Visibility of this session\'s total distance to athletes.  * `always` - Always * `after` - After the session * `never` - Never
     */
    vis_distance?: VisibilityMode;
    /**
     * Visibility of this session\'s goal to athletes.  * `always` - Always * `after` - After the session * `never` - Never
     */
    vis_goal?: VisibilityMode;
    /**
     * Visibility of this session\'s rounds (and exercises) to athletes.  * `always` - Always * `after` - After the session * `never` - Never
     */
    vis_rounds?: VisibilityMode;
    /**
     * Whether this session is currently shared via its public link.
     */
    readonly is_public: boolean;
    /**
     * Unguessable token in the public share URL. Null = never shared. The token authenticates the otherwise-anonymous public view.
     */
    readonly public_token: string | null;
    readonly generated_by_ai: boolean;
    readonly ai_response: string;
    readonly ai_generated_at: string | null;
    debrief?: string;
    ai_athlete_brief?: string;
    readonly created_at: string;
    readonly updated_at: string;
}



