/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EventShareResponse { 
    is_public: boolean;
    public_token: string | null;
    /**
     * Frontend route, e.g. /s/e/<token>. Null when not shared.
     */
    public_url_path: string | null;
}

