/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DebriefRoti } from './debrief-roti';
import { DebriefAttendance } from './debrief-attendance';
import { DebriefRsvp } from './debrief-rsvp';


/**
 * Consolidated post-session debrief for one event (managers only): attendance + ROTI + RSVP summaries, attachment count, and the coach\'s free-text debrief — all in a single read.
 */
export interface EventDebrief { 
    debrief: string;
    attendance: DebriefAttendance;
    roti: DebriefRoti;
    rsvp: DebriefRsvp;
    attachments_count: number;
}

