/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * MM:SS format, e.g. 1:30.
 */
/**
 * @type ExerciseTStart
 * MM:SS format, e.g. 1:30.
 * @export
 */
export type ExerciseTStart = string;

