/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeneratePlanTokensUsed } from './generate-plan-tokens-used';


export interface GeneratePlanResponse { 
    created_count: number;
    deleted_count: number;
    rationale: string;
    model: string;
    tokens_used: GeneratePlanTokensUsed;
}

