/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OverlapStrategyEnum } from './overlap-strategy-enum';


export interface GeneratePlanRequest { 
    date_start: string;
    date_end: string;
    frequency_per_week: number;
    description?: string;
    additional_prompt?: string;
    overlap_strategy?: OverlapStrategyEnum;
}



