/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `manual` - Manual — managers accept/reject each request * `auto` - Auto-accept — every join request is accepted immediately
 */
export enum JoinRequestPolicyEnum {

    Manual = 'manual',

    Auto = 'auto'
}

