/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `pending` - pending * `accepted` - accepted * `rejected` - rejected * `cancelled` - cancelled
 */
export enum MagicActionJoinRequestStatusEnum {

    Pending = 'pending',

    Accepted = 'accepted',

    Rejected = 'rejected',

    Cancelled = 'cancelled'
}

