/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomUserPublic } from './custom-user-public';


export interface Member { 
    readonly id: number;
    firstname: string;
    lastname: string;
    readonly fullname: string;
    email?: string | null;
    phonenumber?: string | null;
    teams?: Array<number>;
    readonly user: CustomUserPublic;
    user_id?: number | null;
    readonly created_at: string;
    readonly updated_at: string;
}

