/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MemberRequest { 
    firstname: string;
    lastname: string;
    email?: string | null;
    phonenumber?: string | null;
    user_id?: number | null;
}

