/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Body of POST /api/v1/auth/password/reset/confirm/. The view decodes `key` (uid + token) and validates `new_password` against Django\'s password validators with the matched user as context.
 */
export interface PasswordResetConfirm { 
    key: string;
    new_password: string;
}

