/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatchedProgramRequest { 
    name?: string;
    date_start?: string | null;
    date_end?: string | null;
    team_id?: number;
    frequency_per_week?: number | null;
    description?: string;
    is_active?: boolean;
}

