/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TrainingTypeEnum } from './training-type-enum';
import { VisibilityMode } from './visibility-mode';


export interface PatchedEventRequest { 
    name?: string;
    goal?: string | null;
    /**
     * This event\'s active training-content type. Seeded at creation from the team-sport / sport cascade; editable by the coach.  * `structured` - Structured (rounds & exercises) * `freeform` - Free text
     */
    training_type?: TrainingTypeEnum;
    /**
     * Free-text training content (sanitized HTML) when training_type=freeform.
     */
    training_richtext?: string;
    /**
     * Where the session takes place (venue, pool, track, address). Always visible to athletes.
     */
    location?: string;
    place_id?: number | null;
    /**
     * Material/gear athletes should bring. Always visible to athletes.
     */
    equipment?: string;
    equipment_item_ids?: Array<number>;
    color?: string;
    date?: string | null;
    hour_start?: string | null;
    hour_end?: string | null;
    total?: number;
    refer_program_id?: number;
    sport_id?: number | null;
    /**
     * Visibility of this session\'s total distance to athletes.  * `always` - Always * `after` - After the session * `never` - Never
     */
    vis_distance?: VisibilityMode;
    /**
     * Visibility of this session\'s goal to athletes.  * `always` - Always * `after` - After the session * `never` - Never
     */
    vis_goal?: VisibilityMode;
    /**
     * Visibility of this session\'s rounds (and exercises) to athletes.  * `always` - Always * `after` - After the session * `never` - Never
     */
    vis_rounds?: VisibilityMode;
    debrief?: string;
    ai_athlete_brief?: string;
}



