/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UnitEnum } from './unit-enum';


/**
 * Read/write serializer for a single Performance row.  `team` and `member` are writable PrimaryKeyRelatedFields on create; on update they are ignored (a performance never moves to another member or team — the view drops them from validated_data in update()). `created_by` is set by the view from request.user and is read-only here.
 */
export interface PatchedPerformance { 
    readonly id?: number;
    team?: number;
    member?: number;
    /**
     * Discipline / test name, e.g. \'100m freestyle\' or \'Cooper test\'.
     */
    label?: string;
    /**
     * Numeric result, interpreted by unit (seconds for time, meters for distance, etc.).
     */
    value?: string;
    unit?: UnitEnum;
    readonly is_lower_better?: boolean;
    /**
     * Date the performance was achieved.
     */
    recorded_on?: string;
    notes?: string;
    readonly created_by?: number;
    readonly created_at?: string;
    readonly updated_at?: string;
}



