/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TeamQuotaStatus } from './team-quota-status';
import { LanguageEnum } from './language-enum';


export interface PatchedMe { 
    readonly id?: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    readonly username?: string;
    readonly email?: string;
    first_name?: string;
    last_name?: string;
    language?: LanguageEnum;
    readonly last_login?: string | null;
    readonly date_joined?: string;
    /**
     * Designates whether the user can log into this admin site.
     */
    readonly is_staff?: boolean;
    /**
     * Designates that this user has all permissions without explicitly assigning them.
     */
    readonly is_superuser?: boolean;
    readonly team_quota?: TeamQuotaStatus;
}



