/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MemberEmail } from './member-email';


export interface PatchedMemberRequest { 
    firstname?: string;
    lastname?: string;
    email?: MemberEmail | null;
    phonenumber?: string | null;
    user_id?: number | null;
}

