/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TeamMinimal } from './team-minimal';


export interface PatchedProgram { 
    readonly id?: number;
    name?: string;
    date_start?: string | null;
    date_end?: string | null;
    readonly team?: TeamMinimal;
    team_id?: number;
    events?: Array<number>;
    frequency_per_week?: number | null;
    description?: string;
    readonly generated_by_ai?: boolean;
    readonly ai_response?: string;
    readonly ai_generated_at?: string | null;
    is_active?: boolean;
    readonly created_at?: string;
    readonly updated_at?: string;
}

