/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Serializer for Note. team/member/author are derived from the URL and the request user; they are read-only here. The \'content\' field is sanitized via bleach on every write.
 */
export interface PatchedNote { 
    readonly id?: number;
    readonly team?: number;
    readonly member?: number;
    /**
     * The coach who wrote this note. SET_NULL if the author account is deleted.
     */
    readonly author?: number | null;
    readonly author_username?: string;
    /**
     * Rich HTML content (sanitized via bleach on save).
     */
    content?: string;
    /**
     * If True, the concerned athlete can read this note (when it is also active). Default False — notes are coach-only unless explicitly shared.
     */
    visible_to_athlete?: boolean;
    readonly is_active?: boolean;
    readonly created_at?: string;
    readonly updated_at?: string;
}

