/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `android` - Android * `ios` - iOS
 */
export enum PlatformEnum {

    Android = 'android',

    Ios = 'ios'
}

