/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LanguageEnum } from './language-enum';


/**
 * Public registration payload for POST /api/v1/auth/register/.  Email-only: there is no username. Uniqueness is enforced against CustomUser.email (the unique constraint is the DB backstop).  `turnstile_token` is required: server-side verification with Cloudflare happens in the view (not here, because we need the request to extract the remote IP). The serializer just enforces presence.
 */
export interface RegisterRequest { 
    email: string;
    password: string;
    first_name: string;
    last_name: string;
    language?: LanguageEnum;
    turnstile_token: string;
}



