/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Body for POST /rounds/{id}/exercises/reorder/.  `exercise_ids` must contain exactly the IDs of the Exercises currently attached to the Round in the desired final order. The view enforces scope/completeness in addition to this serializer\'s syntactic check.
 */
export interface ReorderExercisesRequestRequest { 
    exercise_ids: Array<number>;
}

