/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One athlete\'s mean ROTI vs the squad over the window.
 */
export interface RotiDriftEntry { 
    member_id: number;
    name: string;
    /**
     * Athlete\'s mean ROTI (1..5).
     */
    average: number;
    /**
     * Number of ROTI scores.
     */
    count: number;
    /**
     * average - squad_average.
     */
    delta: number;
    /**
     * One of: high, low, normal.
     */
    flag: string;
}

