/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StatsAttendanceByMember { 
    member_id: number;
    name: string;
    present: number;
    total: number;
    rate: number | null;
    last_present_date: string | null;
    /**
     * Current consecutive-present streak (per-athlete scope only; null on the team aggregate).
     */
    streak?: number | null;
}

