/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatsRotiPoint } from './stats-roti-point';


/**
 * Per-athlete ROTI (return-on-training-investment) trend over the window. Empty series on the team aggregate (ROTI is per athlete).
 */
export interface StatsRoti { 
    series: Array<StatsRotiPoint>;
    average: number | null;
    count: number;
}

