/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Read/write serializer for TeamMembership.  `team` is set by the view from URL kwargs; only `member` is accepted on POST.
 */
export interface TeamMembership { 
    readonly id: number;
    readonly team: number;
    member: number;
    readonly member_username: string;
    readonly member_fullname: string;
    /**
     * When this athlete joined the team.
     */
    readonly joined_at: string;
    /**
     * When this athlete left the team. NULL = currently active.
     */
    readonly left_at: string | null;
    readonly created_at: string;
    readonly updated_at: string;
}

