/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LanguageEnum } from './language-enum';


/**
 * Compact team payload for nested read contexts.
 */
export interface TeamMinimal { 
    readonly id: number;
    readonly name: string;
    readonly language: LanguageEnum;
}



