/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JoinRequestStatusEnum } from './join-request-status-enum';


/**
 * Standard serializer for /join-requests/. Mirrors TeamMembershipSerializer\'s pattern of exposing username/fullname denorms so the manager dashboard can render the requester without a separate /users/{id}/ fetch.
 */
export interface TeamJoinRequestRequest { 
    team: number;
    status?: JoinRequestStatusEnum;
    message?: string;
    response_message?: string;
}



