/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomUserPublic } from './custom-user-public';


/**
 * A single message. ``author`` is the nested public user; ``content`` is sanitized via bleach on every write.
 */
export interface TopicMessage { 
    readonly id: number;
    /**
     * Rich HTML content (sanitized via bleach on save).
     */
    content: string;
    readonly author: CustomUserPublic;
    readonly created_at: string;
}

