/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TrainingSlot } from './training-slot';


/**
 * The team\'s reusable weekly training template.  Body of PUT and shape of GET on /teams/{id}/training-template/. PUT atomically REPLACES the template: existing slots are deleted and recreated from `slots`, and default_pool/season_start/season_end are set on the team.
 */
export interface TrainingTemplate { 
    slots: Array<TrainingSlot>;
    default_pool?: string;
    season_start?: string | null;
    season_end?: string | null;
}

