/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `note_for_coach` - Note added on an athlete * `note_for_athlete` - A note was shared with you * `message_new_topic` - A new topic was created in your team * `message_new_reply` - A new message was posted in a topic
 */
export enum TypeEnum {

    NoteForCoach = 'note_for_coach',

    NoteForAthlete = 'note_for_athlete',

    MessageNewTopic = 'message_new_topic',

    MessageNewReply = 'message_new_reply'
}

