/**
 * Training Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Block JWT login when the user has an unverified primary email.  Legacy users predating allauth integration have no EmailAddress row; they are treated as verified to preserve backwards compatibility (no data migration). Once an EmailAddress exists for a user, the `verified` flag becomes authoritative.
 */
export interface VerifiedTokenObtainPair { 
    username: string;
    password: string;
}

