#!/usr/bin/env bash
# =============================================================================
# Training Manager frontend — Fetch runtime config from AWS SSM into an nginx
# snippet.
#
# Run by tm-frontend-runtime-fetch.service (oneshot) at boot, and by the deploy
# pipeline. Reads /tm-frontend/prod/* (eu-west-1) via the EC2 instance role (the
# unit blanks AWS_*_FILE so root's certbot-route53 keys don't shadow the role)
# and writes an nginx snippet `set $tm_* "...";` that the vhost includes and
# injects into index.html.
#
# The frontend config is PUBLIC (served to the browser) → SSM String only, never
# a secret. Guards: reject values with an internal newline, write atomically
# (0644 root), idempotent (no reload if unchanged), validate `nginx -t` first.
# =============================================================================
set -euo pipefail

SSM_PREFIX="${TM_FRONTEND_SSM_PREFIX:-/tm-frontend/prod}"
AWS_REGION="${AWS_REGION:-eu-west-1}"
OUT_FILE="${TM_FRONTEND_RUNTIME_FILE:-/etc/nginx/snippets/tm-frontend-runtime.conf}"

echo "[frontend-runtime] prefix=$SSM_PREFIX region=$AWS_REGION out=$OUT_FILE"

RAW_FILE="$(mktemp)"
TMP_FILE="$(mktemp)"
trap 'rm -f "$RAW_FILE" "$TMP_FILE"' EXIT

# Fetch raw JSON first. If aws errors (IAM/IMDS/network), set -e stops here and
# the previous $OUT_FILE is left untouched.
aws ssm get-parameters-by-path \
    --path "$SSM_PREFIX" \
    --recursive \
    --region "$AWS_REGION" \
    --output json > "$RAW_FILE"

# Parse JSON -> nginx `set` directives. Program from the heredoc (python3 -),
# data from a file argument: no "program vs data on stdin" clash. Missing keys
# fall back to defaults.
python3 - "$SSM_PREFIX" "$TMP_FILE" "$RAW_FILE" <<'PY'
import json, sys

prefix, out_path, raw_path = sys.argv[1], sys.argv[2], sys.argv[3]
with open(raw_path) as fh:
    params = json.load(fh).get("Parameters", [])

values = {
    "API_BASE_URL": "",
    "SENTRY_DSN": "",
    "SENTRY_ENV": "production",
    "SENTRY_RELEASE": "",
    "FEATURES": "{}",
}

for p in params:
    key = p["Name"][len(prefix):].lstrip("/")
    value = p["Value"].strip("\r\n")
    if "\n" in value or "\r" in value:
        sys.stderr.write(f"ERROR: value for {key} contains an internal newline; refusing.\n")
        sys.exit(1)
    if key in values:
        values[key] = value

# FEATURES must be valid JSON, else fall back to {} (don't break the page). The
# vhost sub_filter injects it WITHOUT quotes (window.__TM_FEATURES=$tm_features
# → literal JS object), but the nginx `set` directive below MUST be quoted (a
# bare {} would be read as an nginx block). nginx strips the quotes when storing
# the variable, so the value stays the raw JSON; escape internal " for nginx.
features = values["FEATURES"].strip() or "{}"
try:
    json.loads(features)
except ValueError:
    sys.stderr.write(f"WARN: FEATURES is not valid JSON ({features!r}); using {{}}.\n")
    features = "{}"
features_nginx = features.replace("\\", "\\\\").replace('"', '\\"')

lines = [
    "# AUTO-GENERATED by deploy/fetch-frontend-runtime-from-ssm.sh",
    f"# Source of truth: AWS SSM {prefix}/* . Manual edits are overwritten on the",
    "# next service restart / deploy.",
    f'set $tm_api_base       "{values["API_BASE_URL"]}";',
    f'set $tm_sentry_dsn     "{values["SENTRY_DSN"]}";',
    f'set $tm_sentry_env     "{values["SENTRY_ENV"]}";',
    f'set $tm_sentry_release "{values["SENTRY_RELEASE"]}";',
    f'set $tm_features       "{features_nginx}";',
]
with open(out_path, "w") as fh:
    fh.write("\n".join(lines) + "\n")
PY

# Idempotence: nothing to do if the snippet is identical (avoids an nginx reload).
if [ -f "$OUT_FILE" ] && cmp -s "$TMP_FILE" "$OUT_FILE"; then
    echo "[frontend-runtime] $OUT_FILE unchanged — no reload needed"
    exit 0
fi

mkdir -p "$(dirname "$OUT_FILE")"
install -m 0644 -o root -g root "$TMP_FILE" "$OUT_FILE"
echo "[frontend-runtime] $OUT_FILE updated"

# Validate the full config (vhost + snippet) before reloading. If KO, don't
# reload (the master keeps running the previous valid config).
if ! nginx -t; then
    echo "ERROR: nginx -t failed after writing $OUT_FILE — skipping reload" >&2
    exit 3
fi

systemctl reload nginx
echo "[frontend-runtime] nginx reloaded"
